import Foundation
import Testing
@testable import BridgeGenCore

@Suite("SwiftStreamEmitter")
struct SwiftStreamEmitterTests {
    let emitter = SwiftStreamEmitter()

    let home = BridgeDescriptor(
        bridgeName: "HomeBridge",
        swiftTypeName: "HomeUseCase",
        methods: [
            .init(name: "fetch", params: [], returnType: .init(swiftType: .simple("HomeOverview"), isVoid: false)),
            .init(
                name: "observe",
                params: [.init(name: "projectId", swiftType: .simple("String"), label: "projectId")],
                returnType: .init(swiftType: .simple("HomeOverview"), isVoid: false),
                kind: .stream(throwing: false)
            ),
        ]
    )

    @Test("Emits a guarded Observation for a plain stream")
    func plainStream() throws {
        let output = try #require(emitter.emit(home))

        #expect(output.hasPrefix("// Generated by bridge-gen from HomeUseCase. Do not edit.\n"))
        #expect(output.contains("#if canImport(SwiftJava)\nimport Foundation\nimport SwiftAndroidCodegen\n"))
        #expect(output.contains("public final class HomeUseCaseObserveObservation: Sendable {"))
        #expect(output.contains("    private let observation: StreamObservation<HomeOverview>"))
        #expect(output.contains("    public init(_ useCase: any HomeUseCase, projectId: String) {"))
        #expect(output.contains("        self.observation = StreamObservation(useCase.observe(projectId: projectId))"))
        #expect(output.contains("    public func next() async -> HomeOverview? {\n        try? await self.observation.next()\n    }"))
        #expect(output.contains("    public func cancel() async {\n        await self.observation.cancel()\n    }"))
        #expect(output.hasSuffix("#endif\n"))
        #expect(!output.contains("fetch"))
    }

    @Test("Throwing streams rethrow from next")
    func throwingStream() throws {
        let bridge = BridgeDescriptor(
            bridgeName: "ListBridge",
            swiftTypeName: "ListUseCase",
            methods: [
                .init(name: "observe", params: [], returnType: .init(swiftType: .simple("ListOverview"), isVoid: false), kind: .stream(throwing: true)),
            ]
        )

        let output = try #require(emitter.emit(bridge))

        #expect(output.contains("    public init(_ useCase: any ListUseCase) {"))
        #expect(output.contains("StreamObservation(useCase.observe())"))
        #expect(output.contains("    public func next() async throws -> ListOverview? {\n        try await self.observation.next()\n    }"))
    }

    @Test("Mirrors external labels")
    func labels() throws {
        let bridge = BridgeDescriptor(
            bridgeName: "SceneBridge",
            swiftTypeName: "SceneUseCase",
            methods: [
                .init(
                    name: "observe",
                    params: [
                        .init(name: "projectId", swiftType: .simple("String"), label: "for"),
                        .init(name: "sceneId", swiftType: .simple("String"), label: nil),
                    ],
                    returnType: .init(swiftType: .simple("Scene"), isVoid: false),
                    kind: .stream(throwing: false)
                ),
            ]
        )

        let output = try #require(emitter.emit(bridge))

        #expect(output.contains("public init(_ useCase: any SceneUseCase, for projectId: String, _ sceneId: String) {"))
        #expect(output.contains("useCase.observe(for: projectId, sceneId)"))
    }

    @Test("Returns nil without stream methods")
    func noStreams() {
        let bridge = BridgeDescriptor(
            bridgeName: "B",
            swiftTypeName: "P",
            methods: [.init(name: "fetch", params: [], returnType: .void)]
        )
        #expect(emitter.emit(bridge) == nil)
    }

    @Test("Output directory is replaced on every run")
    func ownedDirectory() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("bridge-gen-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: directory) }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let stale = directory.appendingPathComponent("Old+AndroidStreams.swift")
        try "stale".write(to: stale, atomically: true, encoding: .utf8)
        let unrelated = directory.appendingPathComponent("Handwritten.swift")
        try "keep".write(to: unrelated, atomically: true, encoding: .utf8)

        let plain = BridgeDescriptor(bridgeName: "B", swiftTypeName: "P", methods: [.init(name: "fetch", params: [], returnType: .void)])
        let written = try SwiftStreamOutput.write([home, plain], to: directory)

        #expect(written == 1)
        #expect(!FileManager.default.fileExists(atPath: stale.path))
        let files = try FileManager.default.contentsOfDirectory(atPath: directory.path).sorted()
        #expect(files == ["Handwritten.swift", "HomeUseCase+AndroidStreams.swift"])
    }
}
