import Foundation

/// Emits the Swift classes that expose a bridged type's stream methods to Kotlin.
public struct SwiftStreamEmitter {
    public init() {}

    public static func fileName(for bridge: BridgeDescriptor) -> String {
        "\(bridge.swiftTypeName)+AndroidStreams.swift"
    }

    /// `nil` when `bridge` has no stream methods.
    public func emit(_ bridge: BridgeDescriptor) -> String? {
        let streams = bridge.methods.filter { if case .stream = $0.kind { true } else { false } }
        guard !streams.isEmpty else { return nil }

        var w = CodeWriter()
        w.line("// Generated by bridge-gen from \(bridge.swiftTypeName). Do not edit.")
        w.line("#if canImport(SwiftJava)")
        w.line("import Foundation")
        w.line("import SwiftAndroidCodegen")
        for method in streams {
            w.line()
            emitObservation(&w, bridge: bridge, method: method)
        }
        w.line("#endif")
        return w.output
    }

    private func emitObservation(_ w: inout CodeWriter, bridge: BridgeDescriptor, method: BridgeDescriptor.Method) {
        guard case let .stream(throwing) = method.kind else { return }
        let element = method.returnType.swiftType.swiftSpelling
        let initParams = (["_ useCase: any \(bridge.swiftTypeName)"] + method.params.map(declaration)).joined(separator: ", ")
        let arguments = method.params.map(argument).joined(separator: ", ")

        w.line("public final class \(bridge.observationTypeName(for: method)): Sendable {")
        w.indented { w in
            w.line("private let observation: StreamObservation<\(element)>")
            w.line()
            w.line("public init(\(initParams)) {")
            w.indented { w in
                w.line("self.observation = StreamObservation(useCase.\(method.name)(\(arguments)))")
            }
            w.line("}")
            w.line()
            if throwing {
                w.line("public func next() async throws -> \(element)? {")
                w.indented { w in w.line("try await self.observation.next()") }
            } else {
                w.line("public func next() async -> \(element)? {")
                w.indented { w in w.line("try? await self.observation.next()") }
            }
            w.line("}")
            w.line()
            w.line("public func cancel() async {")
            w.indented { w in w.line("await self.observation.cancel()") }
            w.line("}")
        }
        w.line("}")
    }

    private func declaration(_ param: BridgeDescriptor.Param) -> String {
        let type = param.swiftType.swiftSpelling
        switch param.label {
        case nil: return "_ \(param.name): \(type)"
        case param.name: return "\(param.name): \(type)"
        case let label?: return "\(label) \(param.name): \(type)"
        }
    }

    private func argument(_ param: BridgeDescriptor.Param) -> String {
        guard let label = param.label else { return param.name }
        return "\(label): \(param.name)"
    }
}

/// Writes generated stream sources into a directory the tool owns.
public enum SwiftStreamOutput {
    static let suffix = "+AndroidStreams.swift"

    /// Deletes every `+AndroidStreams.swift` file in `directory`, then writes one file per bridge with streams.
    @discardableResult
    public static func write(_ bridges: [BridgeDescriptor], to directory: URL) throws -> Int {
        let fm = FileManager.default
        try fm.createDirectory(at: directory, withIntermediateDirectories: true)
        for name in try fm.contentsOfDirectory(atPath: directory.path) where name.hasSuffix(Self.suffix) {
            try fm.removeItem(at: directory.appendingPathComponent(name))
        }

        let emitter = SwiftStreamEmitter()
        var written = 0
        for bridge in bridges {
            guard let source = emitter.emit(bridge) else { continue }
            let file = directory.appendingPathComponent(SwiftStreamEmitter.fileName(for: bridge))
            try source.write(to: file, atomically: true, encoding: .utf8)
            written += 1
        }
        return written
    }
}
